### ISSUE TITLE
Confusion about the role of CsWinRT, some documentation says it's necessary, elsewhere we don't have to use it.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/CsWinRT#1041]
In the documentation you state 
>Managed apps only need a project or package reference to the authored component, and native apps will need some extra steps that we cover in this documentation. 

Let's say I have a managed app, I don't see how I can simply add a reference, the way UWP does it.

That statement seems to contradict what I understand from the documentation as the process of consuming a runtime component - that is, using CsWinRT to create the C# component, which in turn is used by the application. So as I understand it, we need to make a library for the library with no benefit.

Once I've written my runtime component (C++), isn't that an authored component? Why can't it be used simply by adding a reference in my C# project as described above? 

I really do want the scenario where I don't need to use CsWinRT. Am I mistaken in thinking that I have to use CsWinRT?  Because it's pretty awkward to use compared to the UWP technology, and I want to avoid it if at all possible.

**Comment by angelazhangmsft** [comment]
@Gavin-Williams - The [authoring docs](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md) are specifically for authoring a Windows Runtime Component in C#. It sounds like you already have a runtime component written in C++. In this scenario, you will need C#/WinRT to generate a projection and consume the component from C# (in .NET 5 or later). This is due to the [removal of WinMD support](https://docs.microsoft.com/dotnet/core/compatibility/interop/5.0/built-in-support-for-winrt-removed) in .NET 5.

**Comment by Gavin-Williams** [comment]
@angelazhangmsft OK. Thanks for the clarification. I wasn't sure if I was doing unnecessary work and there was an easy way to consume runtime components.
