### ISSUE TITLE
Cannot use reflection to reflect on Windows Metadata files

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/CsWinRT#1067]
**Describe the bug**
Previously I used reflection in .NET Core 3 to read Windows Metadata files (.winmd) however now that .NET has removed built-in WinRT support and requires to use CsWinRT for that, you can no longer use reflection on those files, except once which CsWinRT has created an interop assembly for which isn't easy to at runtime.

**To Reproduce**
1. Load a Windows Runtime assembly using Assembly.Load and use reflection on it.
2. It will fail with System.IO.FileLoadException.

**Expected behaviour**
You should be able to load a Windows Runtime metadata file at runtime and use reflection on it. After all, Windows Metadata files are just a metadata-only .NET assembly (might contain code when written in a .NET language).

**Comment by angelazhangmsft** [comment]
@Jaiganeshkumaran, this is not considered a bug on our end, due to changes in the platform with .NET 5. 

WinMD files are no longer supported with C# reflection. This usage is confusing .NET metadata-only assemblies (still supported) with WinRT metadata assemblies (not supported). The type systems between the two (.NET vs WinRT) are fundamentally different. The user should rely on [ApiInformation](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.ApiInformation?view=winrt-22000) checks instead, as any native language would have to do, and this is what the old WinMD C# reflection support was doing under the hood.

**Comment by Jaiganeshkumaran** [comment]
What should I do to reflect on WinRT APIs then? [ApiInformation](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.ApiInformation?view=winrt-22000) is only for detecting if a type/method/property exists on the system, not a general-purpose reflection system. Even if WinRT is fundamentally different, the file format is based on the ECMA-335 standard which .NET should be able to handle.

**Comment by Scottj1s** [comment]
@Jaiganeshkumaran Can you share what your WinRT reflection scenarios are, beyond existence checks?  It's true that the metadata standard is common, but the implementation is not.  The previous built-in reflection support for WinRT metadata was effectively equivalent to ApiInformation checks.

**Comment by teo-tsirpanis** [comment]
@Jaiganeshkumaran I tried using [`MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext) to load the `.winmd` files and it seems to work.

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran I tried using [`MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext) to load the `.winmd` files and it seems to work.

Good to know. Closing this issue.
