### ISSUE TITLE
When to use EnqueueAsync and TryEnqueue

### ISSUE THREAD

**Issue by kondareddy** [microsoft/CsWinRT#1307]
Please elaborate when to use below methods/cases and it's impact in UI thread.

DispatcherQ.EnqueueAsync(async () =>
           {
               await Xyz();
           });

Await DispatcherQ.EnqueueAsync(async () =>
           {
               await Xyz();
           });

 DispatcherQ.TryEnqueue(async () =>
                {
                    await Xyz();
                });

Actually looking replacement of Invoke and BeginInvoke
https://stackoverflow.com/questions/229554/whats-the-difference-between-invoke-and-begininvoke

**Comment by Sergio0694** [comment]
That StackOverflow question is old and completely outdated. CoreCLR doesn't even support `BeginInvoke` at all anymore, that whole API is completely deprecated now and there is just no reason you should ever want to (or could) use it now 🙂

The `EnqueueAsync` methods you mentioned (I assume you're referring to the extensions from the [Windows Community Toolkit](https://learn.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.dispatcherqueueextensions.enqueueasync)) are just convenience wrappers around `TryEnqueue`, which they use behind the scenes. The main difference is that rather than just using the "enqueue and forget" approach of `TryEnqueue`, they give you a way of easily awaiting for that scheduled callback to complete executing, as well as optionally returning a value produced by it. They also encapsulate the callback into a `try/catch` block, given they return a `Task`, so if that threw an exception it wouldn't crash the whole app like `TryEnqueue` would, but rather it'd just transition the returned `Task` into the faulted state, which would rethrow the exception when awaited.

So just feel free to use whichever is more appropriate depending on your scenario.
You can also see some examples in our [docs here](https://learn.microsoft.com/en-us/windows/communitytoolkit/extensions/dispatcherqueueextensions).
