### ISSUE TITLE
StorageFolder.GetFilesAsync() takes long time

### ISSUE THREAD

**Issue by majinsoft** [microsoft/CsWinRT#1338]
Hello all,
When a directory (StorageFolder) is having 5k+ files the call to GetFilesAsync() take many seconds.
Is there a way to speed-up thing? I already tried the API FindFirstFileExFromApp() but then I need to convert the path to a StorageFile to use it in UWP and this take even more time at the end.
Thank you

**Comment by manodasanW** [comment]
@majinsoft from your post, it sounds like the performance issue you are seeing is with the actual OS API itself rather than CsWinRT.  I would encourage you to provide that feedback in Feedback Hub so that the appropriate team gets the feedback.  With that said, some of the [comments from Raymond here](https://stackoverflow.com/questions/32668822/faster-way-to-get-files-of-a-folder-than-storagefolder-getfilesasync#comment53205378_32668822) may be useful depending on your scenario or you might be able to use other  Win32 file APIs together with FindFirstFileExFromApp rather than converting to a StorageFile if this is an WinAppSDK app.

**Comment by majinsoft** [comment]
It´s an UWP app, so I can´t call any Win32 file API. I sent the feedback with the Feedback Hub, but just checking here if can be something related to CsWinRT. Thank you.
