### ISSUE TITLE
Error message for 'A public type has a namespace that shares no common prefix' doesn't specify the offending type

### ISSUE THREAD

**Issue by jevansaks** [microsoft/CsWinRT#1425]
When using `<CsWinRTComponent>true</>` and tripping this error:

```
1>FooBar.cs(5,30,5,37): error CsWinRT1001: A public type has a namespace ('Foo.Bar.Baz') that shares no common prefix with other namespaces ('MyLibrary'). All types within a Windows Metadata file must exist in a sub namespace of the namespace that is implied by the file name. (https://github.com/microsoft/CsWinRT/tree/master/src/Authoring/WinRT.SourceGenerator/AnalyzerReleases.Unshipped.md)
```

It says what the namespace conflict is but doesn't give the right file/line number or tell me which type is the problem.

**Comment by Sergio0694** [comment]
Some additional context. The issue is this `CheckNamespace` check:

https://github.com/microsoft/CsWinRT/blob/440e357415d808b9d4993d247f2afadff36fe0db/src/Authoring/WinRT.SourceGenerator/DiagnosticUtils.cs#L44-L81

Specifically, this failed check:

https://github.com/microsoft/CsWinRT/blob/440e357415d808b9d4993d247f2afadff36fe0db/src/Authoring/WinRT.SourceGenerator/DiagnosticUtils.cs#L76-L79

This seems to be caused by the fact the syntax receiver is actually detecting all partial types as public:

https://github.com/microsoft/CsWinRT/blob/440e357415d808b9d4993d247f2afadff36fe0db/src/Authoring/WinRT.SourceGenerator/Generator.cs#L251-L255

Which is not correct for two reasons:
- Types that have the `partial` modifer and a non-public accessibility modifier should not be included
  - As in, even though they're partial, we already know they're _definitely_ not public
- The comment says that partial types will be validated with symbols, but that second check seems... Just missing?

Not seeing anything in `CheckNamespace` actually checking the accessibility of those types via the symbols.

**Comment by jevansaks** [comment]
And you should be able to repro by adding this to a CsWinRTComponent:
```c#
namespace Something.Else
{
    internal partial class ThisShouldBeFine
    {
    }
}
```
