### ISSUE TITLE
Perf: Minimize QueryInterface calls, cache AsInternal 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#181]

**Comment by AdamBraden** [comment]
Default Interface of a class is cached, everything else requires a QI, adding to perf and heap pressure.
Investigate options - maintain as a separate lazy member, dictionary, ConditionalWeakTable

**Comment by manodasanW** [comment]
To help validate the performance of QueryInterface scenarios and determine whether caching will help, I implemented the following benchmarks on both a custom type and a real SDK type:
- Call a property on a default interface
- Call a property on a non default interface

As seen in the benchmarks below, it can be seen that there is an order of magnitude difference between accessing  properties on the default interface which today are cached and accessing properties on the non default interface which isn't.  By doing the caching, we will definitely improve performance.  At the same time, we don't want to regress the performance of the first non cached call.  To measure its performance, I added a benchmark which constructs the object and makes a call on the respective interface.  This benchmark has the overhead of the object construction, but will help ensure we see any significant regressions in perf.

**CsWinRT Projection:**

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.20158
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
  [Host]     : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), X64 RyuJIT
  Job-MHJRRD : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), X64 RyuJIT
  Job-YSYGGO : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-CJDMEJ : .NET Core 5.0.0 (CoreCLR 5.0.20.27801, CoreFX 5.0.20.27801), X64 RyuJIT

Platform=X64  Arguments=/p:platform=x64,/p:MsAppxPackageTargets=%temp%\EmptyMsAppxPackage.Targets  

```
|                                        Method |        Job |       Runtime |     Toolchain |         Mean |        Error |       StdDev |       Median | Ratio | RatioSD |
|---------------------------------------------- |----------- |-------------- |-------------- |-------------:|-------------:|-------------:|-------------:|------:|--------:|
|                         QueryDefaultInterface | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |     37.64 ns |     0.774 ns |     1.060 ns |     37.70 ns |  1.00 |    0.00 |
|                         QueryDefaultInterface | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |     30.90 ns |     0.584 ns |     0.547 ns |     30.66 ns |  0.82 |    0.02 |
|                         QueryDefaultInterface | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 |     22.54 ns |     0.432 ns |     0.404 ns |     22.71 ns |  0.60 |    0.02 |
|                                               |            |               |               |              |              |              |              |       |         |
|                      QueryNonDefaultInterface | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |  4,468.15 ns |    89.129 ns |   158.426 ns |  4,416.60 ns |  1.00 |    0.00 |
|                      QueryNonDefaultInterface | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |  3,748.89 ns |    67.855 ns |    60.151 ns |  3,730.48 ns |  0.82 |    0.04 |
|                      QueryNonDefaultInterface | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 | 10,517.25 ns |   325.183 ns |   890.184 ns | 10,196.73 ns |  2.50 |    0.21 |
|                                               |            |               |               |              |              |              |              |       |         |
|                     QueryNonDefaultInterface2 | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |  4,470.19 ns |    88.842 ns |    95.060 ns |  4,452.71 ns |  1.00 |    0.00 |
|                     QueryNonDefaultInterface2 | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |  3,720.20 ns |    44.513 ns |    34.753 ns |  3,729.63 ns |  0.84 |    0.02 |
|                     QueryNonDefaultInterface2 | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 |  9,987.78 ns |   197.442 ns |   211.261 ns |  9,972.11 ns |  2.24 |    0.08 |
|                                               |            |               |               |              |              |              |              |       |         |
|              QueryDefaultInterfaceSetProperty | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |     35.88 ns |     0.406 ns |     0.339 ns |     35.85 ns |  1.00 |    0.00 |
|              QueryDefaultInterfaceSetProperty | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |     28.08 ns |     0.563 ns |     0.552 ns |     28.05 ns |  0.78 |    0.02 |
|              QueryDefaultInterfaceSetProperty | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 |     22.16 ns |     0.291 ns |     0.272 ns |     22.17 ns |  0.62 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|           QueryNonDefaultInterfaceSetProperty | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |  4,365.85 ns |    67.601 ns |    56.450 ns |  4,372.99 ns |  1.00 |    0.00 |
|           QueryNonDefaultInterfaceSetProperty | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |  3,747.60 ns |    69.084 ns |    64.622 ns |  3,771.69 ns |  0.86 |    0.02 |
|           QueryNonDefaultInterfaceSetProperty | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 | 10,091.40 ns |   194.407 ns |   199.641 ns | 10,090.71 ns |  2.32 |    0.06 |
|                                               |            |               |               |              |              |              |              |       |         |
|                      QuerySDKDefaultInterface | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |     48.92 ns |     0.930 ns |     0.870 ns |     49.00 ns |  1.00 |    0.00 |
|                      QuerySDKDefaultInterface | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |     46.76 ns |     0.954 ns |     0.980 ns |     46.86 ns |  0.96 |    0.03 |
|                      QuerySDKDefaultInterface | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 |     39.13 ns |     0.448 ns |     0.374 ns |     39.25 ns |  0.80 |    0.02 |
|                                               |            |               |               |              |              |              |              |       |         |
|                   QuerySDKNonDefaultInterface | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 |  8,907.30 ns |   174.035 ns |   232.332 ns |  8,897.66 ns |  1.00 |    0.00 |
|                   QuerySDKNonDefaultInterface | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 |  7,820.39 ns |   122.775 ns |   108.837 ns |  7,825.55 ns |  0.87 |    0.03 |
|                   QuerySDKNonDefaultInterface | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 | 14,507.80 ns |   220.823 ns |   206.558 ns | 14,569.21 ns |  1.62 |    0.06 |
|                                               |            |               |               |              |              |              |              |       |         |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 | 22,148.49 ns | 1,536.556 ns | 4,530.570 ns | 22,284.48 ns |  1.00 |    0.00 |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 | 19,548.71 ns | 1,439.951 ns | 4,245.727 ns | 19,453.95 ns |  0.88 |    0.03 |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 | 39,816.37 ns |   706.747 ns |   590.166 ns | 39,837.74 ns |  2.58 |    0.09 |
|                                               |            |               |               |              |              |              |              |       |         |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-MHJRRD | .NET Core 2.0 | netcoreapp2.0 | 25,713.83 ns | 1,361.488 ns | 4,014.378 ns | 25,844.84 ns |  1.00 |    0.00 |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-YSYGGO | .NET Core 3.1 | netcoreapp3.1 | 33,429.57 ns | 2,426.910 ns | 7,155.798 ns | 33,745.48 ns |  1.29 |    0.11 |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-CJDMEJ | .NET Core 5.0 | netcoreapp5.0 | 54,035.48 ns | 1,006.082 ns |   941.090 ns | 53,981.72 ns |  2.69 |    0.12 |

Existing .NET projection:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.20158
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
  [Host]             : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  WinMD NetCoreApp31 : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT

Job=WinMD NetCoreApp31  Platform=X64  Arguments=/p:platform=x64,
/p:ApplicationManifest=S:\CsWinRT\Benchmarks\bin\x64\Release\netcoreapp3.1\Benchmarks.manifest,
/p:BenchmarkWinmdSupport=true  
Toolchain=netcoreapp3.1-native  

```
|                                        Method |      Mean |     Error |    StdDev |
|---------------------------------------------- |----------:|----------:|----------:|
|                         QueryDefaultInterface |  10.92 ns |  0.250 ns |  0.432 ns |
|                      QueryNonDefaultInterface |  11.58 ns |  0.259 ns |  0.288 ns |
|                     QueryNonDefaultInterface2 |  14.57 ns |  0.294 ns |  0.275 ns |
|              QueryDefaultInterfaceSetProperty |  10.61 ns |  0.214 ns |  0.200 ns |
|           QueryNonDefaultInterfaceSetProperty |  10.34 ns |  0.235 ns |  0.279 ns |
|                      QuerySDKDefaultInterface |  30.35 ns |  0.464 ns |  0.434 ns |
|                   QuerySDKNonDefaultInterface |  32.78 ns |  0.355 ns |  0.332 ns |
|    ConstructAndQueryDefaultInterfaceFirstCall | 871.73 ns | 13.333 ns | 11.134 ns |
| ConstructAndQueryNonDefaultInterfaceFirstCall | 939.55 ns | 18.596 ns | 41.593 ns |

**Comment by manodasanW** [comment]
My initial attempt at this was to declare a lazy variable for each interface, but I ran into issues where a interface can be implemented on a class using the full name with namespaces in its name which weren't acceptable as variable names due to the colons.  Removing the namespace and just using the interface name wasn't an acceptable workaround as a class can implement 2 different interfaces with the same name from 2 different namespaces.  Due to this I ended up using a dictionary to store the lazy variables.  Below are the results from that and we can see a significant improvement from before on the non default interfaces compared to before.  We are closer to the time it takes on the default interface, but not the same due to the dictionary lookups.  I experimented out with a couple different keys for the dictionary lookup to improve hashing time, but they didn't have a significant difference.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.20159
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.5.20279.10
  [Host]     : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), X64 RyuJIT
  Job-PTBNCW : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), X64 RyuJIT
  Job-WPSDBU : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-MPBDUP : .NET Core 5.0.0 (CoreCLR 5.0.20.27801, CoreFX 5.0.20.27801), X64 RyuJIT

Platform=X64  Arguments=/p:platform=x64,/p:MsAppxPackageTargets=%temp%\EmptyMsAppxPackage.Targets  

```
|                                        Method |        Job |       Runtime |     Toolchain |         Mean |        Error |       StdDev |       Median | Ratio | RatioSD |
|---------------------------------------------- |----------- |-------------- |-------------- |-------------:|-------------:|-------------:|-------------:|------:|--------:|
|                         QueryDefaultInterface | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     34.20 ns |     0.503 ns |     0.393 ns |     34.27 ns |  1.00 |    0.00 |
|                         QueryDefaultInterface | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     28.97 ns |     0.377 ns |     0.315 ns |     28.97 ns |  0.85 |    0.01 |
|                         QueryDefaultInterface | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     23.74 ns |     0.483 ns |     0.452 ns |     23.70 ns |  0.69 |    0.02 |
|                                               |            |               |               |              |              |              |              |       |         |
|                      QueryNonDefaultInterface | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     66.65 ns |     0.947 ns |     0.790 ns |     66.83 ns |  1.00 |    0.00 |
|                      QueryNonDefaultInterface | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     53.44 ns |     0.961 ns |     0.852 ns |     53.40 ns |  0.80 |    0.02 |
|                      QueryNonDefaultInterface | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     46.68 ns |     0.724 ns |     0.642 ns |     46.77 ns |  0.70 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|                     QueryNonDefaultInterface2 | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     60.04 ns |     0.775 ns |     0.647 ns |     60.04 ns |  1.00 |    0.00 |
|                     QueryNonDefaultInterface2 | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     53.53 ns |     0.746 ns |     0.661 ns |     53.71 ns |  0.89 |    0.02 |
|                     QueryNonDefaultInterface2 | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     49.20 ns |     0.653 ns |     0.610 ns |     49.37 ns |  0.82 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|              QueryDefaultInterfaceSetProperty | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     34.55 ns |     0.237 ns |     0.198 ns |     34.51 ns |  1.00 |    0.00 |
|              QueryDefaultInterfaceSetProperty | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     28.02 ns |     0.521 ns |     0.462 ns |     28.12 ns |  0.81 |    0.01 |
|              QueryDefaultInterfaceSetProperty | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     20.77 ns |     0.270 ns |     0.239 ns |     20.80 ns |  0.60 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|           QueryNonDefaultInterfaceSetProperty | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     63.67 ns |     1.111 ns |     0.928 ns |     63.73 ns |  1.00 |    0.00 |
|           QueryNonDefaultInterfaceSetProperty | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     55.17 ns |     1.114 ns |     2.038 ns |     54.48 ns |  0.89 |    0.04 |
|           QueryNonDefaultInterfaceSetProperty | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     47.54 ns |     0.752 ns |     0.666 ns |     47.47 ns |  0.75 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|                      QuerySDKDefaultInterface | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     48.19 ns |     0.402 ns |     0.356 ns |     48.15 ns |  1.00 |    0.00 |
|                      QuerySDKDefaultInterface | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     46.25 ns |     0.929 ns |     1.106 ns |     45.77 ns |  0.96 |    0.02 |
|                      QuerySDKDefaultInterface | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     41.45 ns |     0.510 ns |     0.426 ns |     41.62 ns |  0.86 |    0.01 |
|                                               |            |               |               |              |              |              |              |       |         |
|                   QuerySDKNonDefaultInterface | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 |     77.07 ns |     1.112 ns |     0.985 ns |     77.26 ns |  1.00 |    0.00 |
|                   QuerySDKNonDefaultInterface | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 |     74.81 ns |     0.937 ns |     0.877 ns |     75.09 ns |  0.97 |    0.01 |
|                   QuerySDKNonDefaultInterface | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 |     75.24 ns |     1.012 ns |     0.897 ns |     75.26 ns |  0.98 |    0.02 |
|                                               |            |               |               |              |              |              |              |       |         |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 | 26,426.61 ns | 1,527.908 ns | 4,505.072 ns | 27,896.69 ns |  1.00 |    0.00 |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 | 23,087.85 ns | 1,359.926 ns | 4,009.772 ns | 23,929.69 ns |  0.88 |    0.08 |
|    ConstructAndQueryDefaultInterfaceFirstCall | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 | 40,986.98 ns |   608.244 ns |   568.952 ns | 41,179.08 ns |  2.21 |    0.12 |
|                                               |            |               |               |              |              |              |              |       |         |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-PTBNCW | .NET Core 2.0 | netcoreapp2.0 | 28,496.25 ns | 1,749.337 ns | 5,157.959 ns | 28,244.29 ns |  1.00 |    0.00 |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-WPSDBU | .NET Core 3.1 | netcoreapp3.1 | 25,546.89 ns | 1,889.043 ns | 5,569.887 ns | 25,033.88 ns |  0.89 |    0.05 |
| ConstructAndQueryNonDefaultInterfaceFirstCall | Job-MPBDUP | .NET Core 5.0 | netcoreapp5.0 | 53,269.78 ns | 1,040.539 ns |   868.897 ns | 53,056.71 ns |  2.55 |    0.08 |
