### ISSUE TITLE
`GeneratedBindableCustomProperty` does not support records

### ISSUE THREAD

**Issue by devsko** [microsoft/CsWinRT#1838]
**Describe the bug**

`GeneratedBindableCustomProperty` attributes on records are completely ignored.

**To Reproduce**

```
[GeneratedBindableCustomProperty]
public partial record Language(string Name, int Value);
```
generates no code for bindable custom properties of `Language`

**Expected behavior**

This should work the same way as for classes.

**Version Info**

CsWinRT 2.1.6

**Comment by Sergio0694** [comment]
The issue is because of this syntax filter:

https://github.com/microsoft/CsWinRT/blob/445b4f6511164793869e07346ec8497f4f9cd65a/src/Authoring/WinRT.SourceGenerator/AotOptimizer.cs#L146-L152

Which is only gathering `ClassDeclarationSyntax` items. Not sure if that's intentional? If we wanted to fix this, we'd probably need to update all the other filters as well, such as the one for vtable generators. Currently they all have the same filter on just class declarations.
