### ISSUE TITLE
Exception on trying to read string value

### ISSUE THREAD

**Issue by ojhad** [microsoft/CsWinRT#278]
Here is a [repro project](https://github.com/microsoft/CsWinRT/files/4630125/ReproProject.zip). Keep changing the combobox selection using the keyboard arrow keys. After a little bit `WindowsCompareStringOrdinal` will throw an exception when passing in a string value that is being retrieved from managed code. Screenshot of the stack is below:

![image](https://user-images.githubusercontent.com/6562139/81969228-719ce580-95d2-11ea-8f3a-680a8775a017.png)

**Comment by Scottj1s** [comment]
@ojhad This looks to have been a WinUI issue, as I can no longer repro with a newer version (3.0.0-preview2.200713.0).  I'll leave open for a few days if you want to confirm.

**Comment by alwu-msft** [comment]
@Scottj1s This still repros; I've been able to repro it consistently using the Desktop Xaml Controls Gallery on Preview 3.

1. Navigate to the CalenderView sample in Xaml Controls Gallery
2. Give keyboard focus to the "Language" combo box
3. Quickly change the SelectedItem by holding down the up/down arrow keys, changing direction as the end of the list is reached
4. Eventually (will probably take several loops through the list) the aforementioned AV will be triggered

**Comment by Scottj1s** [comment]
@alwu-msft, yes this issue was ultimately fixed, but didn't make it into WinUI 3 Preview 3.  It was published with [cswinrt 1.1.0](https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/1.1.0), PR [551](https://github.com/microsoft/CsWinRT/pull/551). 
 The latest Windows SDK Interop in [.NET SDK 5.0.1 or later](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.1/5.0.1.md), should address it.
