### ISSUE TITLE
Evaluate pros and cons of switching geometry types from double to float

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#280]
Having switched Point, Rect, Size from double to float (see #198), we can assess cost-benefit.

**Comment by dotMorten** [comment]
I'm seeing 100s of build errors as well because of this change. Rect and Point is heavily used for performing layout, but almost everything else is done in doubles, so you're forced to making the casts almost everywhere in your code. IMHO if this change really is needed, it needs to be everywhere, including Width/Height/ActualWidth/ActualHeight/Thickness/GridLength etc etc.
And I'd have to if-def all those cast just for WinUI

**Comment by michael-hawker** [comment]
Yup, changing this now seems like it'll cause a lot of friction for those migrating their existing WUX projects, and part of the selling point is it's supposed to be an easy transition. 

As we've been moving forward with the Toolkit it's been looking more and more like just the namespace changes to update (and the re-target to .NET 5), but this was definitely a  step backwards.

**Comment by sylveon** [comment]
Width/Height and friends are doubles in the Windows Runtime types, not just the projections, changing this would affect all consumers, no matter the language. Code using the Python, C++ and Rust projections would all have to be updated as well.

**Comment by michael-hawker** [comment]
Tagging the right Toolkit Alex as well @azchohfi. FYI @Scottj1s

**Comment by yoshiask** [comment]
@sylveon Why would this affect other languages? I thought this was an issue with the C# projection?

**Comment by sylveon** [comment]
IFrameworkElement uses doubles. It's only Point/Size/Rect that uses floats but where incorrectly projected as doubles.

@dotMorten's suggestion would require changing IFrameworkElement to use floats, which would break every consumer. (I guess that adjusting the projection of those to use floats as well could work, rather than changing the API surface)
![image](https://user-images.githubusercontent.com/6440374/82492057-9520ce00-9ab3-11ea-8866-a1fa31e715d6.png)

**Comment by hshristov** [comment]
I hit the same issue. Migrating library to WinUI Win32 led to 198 errors due to a need to explicit cast.

Do all types need to be projected? I mean can't we have structs like Point, Size, Rect that are only in the C# world and only when they are sent to C++ they are converted to float?

**Comment by MikeHillberg** [comment]
We're generally placing a high priority on compat in WinUI3, focusing instead on adding support for Desktop apps and on reaching earlier versions of Win10. The reason we've considered this incompatibility with Point/Rect/Size despite that is that, as has been said here, it's specifically part of .Net5 support for WinRT rather than part of WinUI or the underlying Windows APIs. We didn't consider changing With/Height, margins, etc.

**Comment by yoshiask** [comment]
> reaching earlier versions of Win10
I presume this excludes Windows Mobile, even if WinUI 3 does eventually support 15063?

**Comment by dotMorten** [comment]
Yeah I withdraw my suggestion to change the other values to float as well.
I'd rather WinUI introduces new double-precision point/rect/float in the WinUI namespaces and use those for layout instead.

**Comment by michael-hawker** [comment]
🦙 Linking back to the original discussion in the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/2047) that started this conversation and discussion to tie things together.

**Comment by Scottj1s** [comment]
Thanks for the feedback, folks.  We've reviewed the switch from double to float properties on Rect, Point, and Size.  While it makes the projection technically "correct", it creates too much impedance with other double properties and variables, and it creates major compatibility issues.  So we've decided to revert the change.

**Comment by dotMorten** [comment]
@Scottj1s Was any thought giving to [this proposal](https://github.com/microsoft/CsWinRT/issues/280#issuecomment-631711569) ?

It seems to me that would fix both problems. Keeping compat + getting the right projection across, not to mention there'lbe less use of the Windows.* namespace within the UI controls, which IMHO makes way more sense.

**Comment by hansmbakker** [comment]
@dotMorten can it be that by accident you linked to this issue instead of another proposal?

**Comment by sylveon** [comment]
They linked a specific comment

**Comment by Scottj1s** [comment]
@dotMorten, yes we discussed your proposal specifically and felt that changing the namespace of geometry types was at least as disruptive as changing the property types.  Keep in mind that the WinRT type definitions are shared by other language projections too (like C++/WinRT), and so all of them would be affected by a change to the ABI.  In addition, the ripple would move through to implementations.  Any WinRT component that formerly used W.F.Rect, Point, and Size as parameters, properties, or nested struct members, would have to update code.

**Comment by dotMorten** [comment]
> Any WinRT component that formerly used W.F.Rect, Point, and Size as parameters, properties, or nested struct members, would have to update code.

That's not true. I was advocating for keeping that type around, and WinUI only would introduce a new point/rect type that'll only be used by WinUI where you're already requiring us to change namespaces throughout.
Any code that was using these types not for running layout in WinUI wouldn't have to change.

**Comment by stevenbrix** [comment]
> That's not true. I was advocating for keeping that type around, and WinUI only would introduce a new additional point/rect type that'll only be used by WinUI where you're already requiring us to change namespaces throughout.

But it's more challenging for C++. They would have the same experience that you did if we moved the actual underlying type to `double` instead of `float`. It wouldn't be a simple namespace change for them.

What if in .NET we projected these to use the WPF types, like `System.Windows.Rect`? C++ code uses `Windows.Foundation.Rect`. Then at least there wouldn't be a discrepancy between the `Windows.Foundation.Rect` type between C++ and .NET. Client C# code would just be a namespace change.

We could even keep the `Windows.Foundation.Rect` type and devise a way for a WinRT API to say "no really, use this type". Or maybe it would be the latter. The default would be to properly project `Windows.Foundation.Rect`, but we could pass in a param to cswinrt that says "project `Windows.Foundation.Rect` to `System.Windows.Rect`" that would be used by WinUI.

**Comment by MikeHillberg** [comment]
Projecting to WPF Rect would mean that your WinUI app would have to reference WindowsBase.dll, and would have a 'using' that would light up IntelliSense with conflicts like DependencyObject and Vector.

We could add new Point/Rect/Size types to the Microsoft.UI.Xaml namespace, but we have a naming guideline against duplicate types, even if the namespace makes them unique, because they create confusion. (No guideline is perfect but we've tried hard and come very close on that one.) We could fix that by making these e.g. 'PointD', but that would be another break.

**Comment by dotMorten** [comment]
@stevenbrix
> But it's more challenging for C++.  They would have the same experience that you did if we moved the actual underlying type to double instead of float

Fair point. But wouldn't it actually mean they'd be removing a bunch of unnecessary float-to-double casts? The reason I found this change so disruptive is that the use of point and rect in controls is that everything else in the layout part is working in doubles (width, height, size, margin, padding etc), and suddenly you use floats to transform points and rects, and to arrange them. It just seems to me that it's wrong to use float-based rects to perform measure/arrange, when everything else is double (regardless of whether the precision really matters).

**Comment by sylveon** [comment]
Float to double is implicit in C++

**Comment by stevenbrix** [comment]
> Projecting to WPF Rect would mean that your WinUI app would have to reference WindowsBase.dll, and would have a 'using' that would light up IntelliSense with conflicts like DependencyObject and Vector.

There is a shim of WindowsBase.dll that exists in `Microsoft.NETCore.App` that has some `System.IO.Packaging` APIs. I was thinking we could add these types to them so that there aren't conflicts

**Comment by Scottj1s** [comment]
@stevenbrix - but what happens at the ABI?  Projecting to WPF types that use double (which is what we now have again) doesn't resolve the root issue - floats across the ABI.  To solve that, we need new double types in WinRT namespaces (i.e., not System.Windows) and much breaking change, even if restricted to just WinUI types.
