### ISSUE TITLE
Possibility to Consume Windows Runtime Components

### ISSUE THREAD

**Issue by AngelMunoz** [microsoft/CsWinRT#301]
Hello there.

Right now if I wanted to make a shared library for the WinRT API that let you consume it in the language you want (C++, C#, VB) I would make a Window Runtime Component like this

![image](https://user-images.githubusercontent.com/8684875/84173676-da914500-aa3a-11ea-90e0-016c0369b9a3.png)

the main motivation for this question is that there may be libraries that target both UWP and .Net (LibVLCSharp  comes to my mind right now)

Is the CsWinRT projection going to allow us to consume these kinds of libraries?
or is there a different path that will be needed for this kind of use cases?

I think this issue might be related to this https://github.com/microsoft/CsWinRT/issues/290

**Comment by BenJKuhn** [comment]
This relates to #309, how components can be authored, and ties to the version of the runtime being used. The short answer is that these libraries would need to be recompiled to target the .NET 5 CLR.

The projection for .NET Core 3 is integrated into the runtime. The .WINMD file produced by the project type referenced above is a single assembly containing both winmd type representations, and implementation classes. If you run ILDASM on that assembly, you'll find that that although it's a well-formed ECMA-335 assembly, the way types are represented is quite distinct from how they are represented in a typical .NET assembly. The CLR & compiler do some special work to produce and load those assemblies and present them in a natural way to a C# developer. 

For targeting .NET 5 C# /WinRT will have a similar authoring experience, but with a very different build & packaging model. The C# WinRT tooling here will produce normal .NET assemblies as well as a separate WinMD that contains no IL code. We'll also have a stub DLL similar to earlier versions of .NET so that unmanaged components written in other languages can call the .NET 5 components. However, the .NET 5 CLR will not be able to load the  merged WinMD files produced by the previous toolchain. Hence the need to rebuild & package exiting libraries for .NET 5.
