### ISSUE TITLE
Provide a fully embedded WinRT interop option

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [microsoft/CsWinRT#304]
There are scenarios where the developer would like to use a WinRT API without polluting/altering their dependencies. This could potentially be limited to cases where the usage of the WinRT API is entirely internal to the library.

It would be nice if the CsWinRT tool could provide a comprehensive WinRT interop scenario, that is internal to the assembly, in the form of just source code - no `WinRT.Runtime.dll` dependency.

/cc @jkotas @richlander @clairernovotny

**Comment by StephenHodgson** [comment]
To extend this a bit, it would also be interesting to see this on a namespace scope as well.

**Comment by jkoritzinsky** [comment]
For the embedded scenario, here's a quick writeup of the proposal discussed over email:

Provide a Microsoft.CsWinRT.Runtime.Embedded.Sources package that has cswinrt.exe, a copy of the WinRT.Runtime sources all marked as internal with modifications to not register the ComWrappers instance globally, and a file that includes an attribute, `[assembly:IncludesEmbeddedWinRTProjection]`. When the WinRT.Runtime code tries to look up a type from its WinRT name, it will first check if the assembly it is in has this attribute. If it does, it will only search this assembly and the (local copy of the) type mapping registrations for the type. If it doesn't have the attribute, it will search every loaded assembly (as is the current behavior today) **except** assemblies with the `IncludesEmbeddedWinRTProjectionAttribute` attribute. As a result, embedded WinRT projections will only know about the types that were projected with them, and the global projections will be discovered correctly by the global ComWrappers instance.

**Comment by BenJKuhn** [comment]
Clearing the milestone on this based on current timeline & resourcing.

**Comment by dotMorten** [comment]
With .NET Core 3.1, I was able to use reflection to detect access to WinRT APIs and light them up if I'm running on Windows. This was great because I relied on WinRT APIs available since Windows 8.0.
With .NET5, reflection to WinRT is no longer supported, and the only way to call WinRT APIs are by targeting net5-windows10.0.17763. This works great for building windows apps, but it works pretty poorly for building cross-platform .NET apps, or building class libraries. Sure I can multi-target, but I'd prefer just targeting net5, because if a user is targeting `net5.0` or even `net5.0-windows`, it'll fallback to the netcoreapp3.1 assembly which is likely still using reflection into WinRT APIs and will fail on .NET 5. I covered some of that here: https://github.com/microsoft/CsWinRT/issues/458

My thought was to build my own WinRT Projection and embed into my assembly, and throw some try/catch and OS checks around it, so I that way would detect support for those APIs and use them. However I didn't have much luck with that.

So I made the following project to get access to GeoLocation APIs, and compiled it:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="0.8.0" PrivateAssets="All" />
  </ItemGroup>
  <PropertyGroup>
    <CsWinRTIncludes>
      Windows.Devices.Geolocation;
      Windows.Foundation.Metadata.ContractVersion;
      Windows.Foundation.UniversalApiContract;
      Windows.Foundation.Metadata.DualApiPartition;
      Windows.Foundation.Metadata.MarshalingBehavior;
      Windows.Foundation.Metadata.MarshalingType;
      Windows.Foundation.Metadata.Activatable;
      Windows.Foundation.Metadata.Static;
      Windows.Foundation.Metadata.Threading;
      Windows.Foundation.Metadata.ThreadingModel;
      Windows.Foundation.Metadata.Muse;
      Windows.Foundation.Metadata.ExclusiveTo;
      Windows.Foundation.Metadata.ApiContract;
      Windows.Foundation.Metadata.AttributeName;
      Windows.Foundation.Metadata.AllowMultiple;
      Windows.Foundation.IAsyncOperation;
      Windows.Foundation.TypedEventHandler;
      Windows.Foundation.UniversalApiContract;
      Windows.Foundation.FoundationContract;
      Windows.Foundation.IAsyncInfo;
      Windows.Foundation.IAsyncAction;
      Windows.Foundation.AsyncStatus;
      Windows.Foundation.AsyncActionCompletedHandler;
      Windows.Foundation.AsyncActionProgressHandler;
      Windows.Foundation.AsyncActionWithProgressCompletedHandler;
      Windows.Foundation.AsyncOperationProgressHandler;
      Windows.Foundation.AsyncOperationCompletedHandler;
      Windows.Foundation.AsyncOperationWithProgressCompletedHandler;
    </CsWinRTIncludes>
    <CsWinRTGeneratedFilesDir>$(OutDir)</CsWinRTGeneratedFilesDir>
    <CsWinRTWindowsMetadata>sdk</CsWinRTWindowsMetadata>
    <CsWinRTGenerateProjection>true</CsWinRTGenerateProjection>
  </PropertyGroup>
</Project>
```
However, because it generates public classes, but the `WinRT.cs` and `WinRT_Interop.cs` files have all types internal (but those types are exposed in the generated classes) I get the following build errors:,
```
`>\obj\Debug\net5.0\Generated Files\Windows.Foundation.Metadata.cs(30,16,30,36): error CS0051: Inconsistent accessibility: parameter type 'Platform' is less accessible than method 'ActivatableAttribute.ActivatableAttribute(uint, Platform)'
1>\obj\Debug\net5.0\Generated Files\Windows.Foundation.Metadata.cs(33,16,33,36): error CS0051: Inconsistent accessibility: parameter type 'Platform' is less accessible than method 'ActivatableAttribute.ActivatableAttribute(Type, uint, Platform)'
1>\obj\Debug\net5.0\Generated Files\Windows.Foundation.Metadata.cs(114,16,114,31): error CS0051: Inconsistent accessibility: parameter type 'Platform' is less accessible than method 'StaticAttribute.StaticAttribute(Type, uint, Platform)'
```

My main problem in the first place is that it generates public classes. I want them all to be internal, as I don't actually want to expose these methods, (doesn't seem like the source generator has that option) but just use them internally in a light-up way. There's just no reason to embed WinRT types and expose them in your class library - if you needed that in your app, just target the TFM that include WinRT APIs.

I then took the generated code from the obj folder and embedded them in a class library, and changed all public classes to internal. Now things actually do compile, but sadly I'm getting bad crashes at runtime, and in addition I'm forced to deploy a WinRT dependency as well (`Microsoft.Windows.CsWinRT`).
```cs
            WinRT.ComWrappersSupport.RegisterProjectionAssembly(typeof(Program).Assembly);
            Geolocator g = new Geolocator(); //OK
            g.DesiredAccuracy = PositionAccuracy.Default; // BOOM!
```
![image](https://user-images.githubusercontent.com/1378165/96054344-501c8000-0e36-11eb-91ee-5e4b410523d1.png)

**Comment by tthiery** [comment]
I have the use case of "the usage of the WinRT API is entirely internal to the library". I abstract the Bluetooth LE Stack (I have four implementations in the project) and WinRT is one of the implementations. Currently the TFM `net5.0-windows....` of .NET is forcing itself into the application domain which I would prefer to have a single TFM (`net5.0`). I tried an AssemblyLoadContext Plugin approach which worked, however, the consequent packaging is just an unneeded hassle.

**Comment by angelazhangmsft** [comment]
Embedded support is now available with [C#/WinRT v1.4.1](https://github.com/microsoft/CsWinRT/releases/tag/1.4.1.211117.1)! These [docs](https://github.com/microsoft/CsWinRT/blob/master/docs/embedded.md) and [samples](https://github.com/microsoft/CsWinRT/tree/master/src/Samples/TestEmbedded) provide more details on how to use the support.

**Comment by E021ntox** [comment]
I’m experimenting with CsWinRT embedded support and trying to include `Windows.ApplicationModel.Package` in my project. However, once I reference this type, the generated projection seems to pull in a very large dependency chain (e.g. Windows.Foundation, Windows.System, Windows.Storage, etc.). How to solve this?

		<CsWinRTIncludes>
			Windows.ApplicationModel.Package;
			Windows.ApplicationModel.AddResourcePackageOptions;
			Windows.ApplicationModel.AppInstallerInfo;
			Windows.ApplicationModel.FindRelatedPackagesOptions;
			Windows.ApplicationModel.IPackageCatalogAddOptionalPackageResult;
			Windows.ApplicationModel.IPackageCatalogAddResourcePackageResult;
			Windows.ApplicationModel.IPackageCatalogRemoveOptionalPackagesResult;
			Windows.ApplicationModel.IPackageCatalogRemoveResourcePackagesResult;
			Windows.ApplicationModel.IPackageCatalog;
			Windows.ApplicationModel.IPackageContentGroupStagingEventArgs;
			Windows.ApplicationModel.IPackageContentGroup;
			Windows.ApplicationModel.AppInstallerPolicySource;
			Windows.ApplicationModel.IAppInstallerInfo;
			Windows.ApplicationModel.IFindRelatedPackagesOptions;
			Windows.ApplicationModel.IPackageId;
			Windows.ApplicationModel.IPackageInstallingEventArgs;
			Windows.ApplicationModel.IPackageStagingEventArgs;
			Windows.ApplicationModel.IPackageStatusChangedEventArgs;
			Windows.ApplicationModel.IPackageStatus;
			Windows.ApplicationModel.IPackageUninstallingEventArgs;
			Windows.ApplicationModel.IPackageUpdateAvailabilityResult;
			Windows.ApplicationModel.IPackageUpdatingEventArgs;
			.....lots of Windows.xxx
		</CsWinRTIncludes>

**Comment by E021ntox** [comment]
@jevansaks thanks!

**Comment by E021ntox** [comment]
https://github.com/microsoft/CsWinRT/issues/1074#issuecomment-2063327350 Same issue.

**Comment by dongle-the-gadget** [comment]
@E021ntox Unfortunately this is the way. In addition, embedded mode will be dropped starting with CsWinRT 3.0
