### ISSUE TITLE
Perf: Minimize Reflection: Register assemblies with RCWs using a module initializer

### ISSUE THREAD

**Issue by jkotas** [microsoft/CsWinRT#312]
The algorithm to discover the runtime type to use for RCW uses reflection and searches for the type in all loaded assemblies. Searching all loaded assemblies in this way is a well-known source of bad performance problems.

Consider registering assemblies that contain RCWs in a global list using a module initializer. It should reduce the number of assemblies that are searched this way significantly.

**Comment by weltkante** [comment]
> Searching all loaded assemblies in this way is a well-known source of bad performance problems.

Just an additional reason to avoid this: depending on how you traverse types this can also crash the process by trying to resolve references which are (intentionally) not there or not loadable (x86/x64 instead of AnyCPU).

**Comment by Scottj1s** [comment]
see also #136

**Comment by jkoritzinsky** [comment]
This is no longer just a perf-related issue. It looks like a common pattern in the .NET world for cross-platform assemblies was to define a .NET type that wrapped a WinRT object through reflection. Some of these users, including ArcGIS, used the exact same namespace and type name. As a result, we're seeing crashes because WinRT.Runtime is discovering these wrapping types instead of the actual projection type. Implementing this will ensure that we don't accidentally discover these wrapper types.

**Comment by jkoritzinsky** [comment]
This will also require a compiler toolset update. (Module initializers came out with VS 16.8 Preview 1 whereas we're using the toolset from VS 16.7)

**Comment by AdamBraden** [comment]
@jkoritzinsky - please confirm if there is anything in this category that is not addressed by your PR? Do we need to be tracking additional work?

**Comment by jkoritzinsky** [comment]
My PR fully implements this feature.
