### ISSUE TITLE
Add WinRT.Host to nuget package for C# authoring

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/CsWinRT#474]
Need this in 1.0 for "preview" of the authoring experience.

**Comment by Scottj1s** [comment]
The desired behavior here is such that when a C# component is built, it:

- Embeds winrt.host.dll, and arch-specific winrt.host.shim.dlls in the packaging
- Causes any native project referencing the C# component to binplace these

**Comment by j0shuams** [comment]
per discussion, we should stage the work:

add winrt.host.dlls, winrt.host.shim.dll and disable all references to these, since no project that references the cswinrt nuget will ever directly consume them. check this is in to unblock partners to manually stage, per Adam's authoring sample.
add component-specific props/targets files that:
a. are ignored by non-component projects
b. are bundled into component project packages (this may require some manual nuspec entries)
c. provide logic for staging arch-specific winrt.host.dll and winrt.host.shim.dll for native referencing projects
Any of the logic in (2) above that cannot be fully automated should be documented in the repo and brief mention made in the nupkg readme.txt (e.g., "for information on creating a C# WinRT component package, see this link...")

**Comment by j0shuams** [comment]
https://github.com/microsoft/CsWinRT/pull/582#discussion_r525309892
