### ISSUE TITLE
C#/WinRT background and architecture guidance

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/CsWinRT#546]
We need more background information for why C#/WinRT exists, background and underlying technologies (COM), and updating/leveraging existing content.

Create the plan to understand the gaps, update Readme, consider creating a BackgroundInfo.md that leverages existing content, etc.

**Comment by j0shuams** [comment]
I think it would help if we gave more definition to "projection assemblies" and explained (albeit at a high-level) more of what the projections are. 

An attempt/example: "We make ABI types which are your code turned into interface(s), and we make vtables within these types so that your functions (and thus objects) can be called (used) in COM. Then, any WinRT compatible language can access your programs." 

It might help to describe in the Authoring/End-to-End samples: how CsWinRT is coming into play.

**Comment by angelazhangmsft** [comment]
I agree with adding more details to the Architecture section about what a projection is, and explaining how cswinrt works with the diagrams.

For the Installing/running section we could add steps for building to make it more clear:
- Open a Visual Studio Developer command prompt pointing at the repo.
- Run `build.cmd`.
- Open the project in Visual Studio by running `devenv cswinrt.sln` from the same command prompt.

**Comment by Nuklon** [comment]
@AdamBraden / others
Does this for .NET 5.0 also mean that the rather large Microsoft.Windows.SDK.NET.dll must always be included? Would be nice to get some details on this, I think it's somewhat related to https://github.com/microsoft/CsWinRT/issues/304.

**Comment by AdamBraden** [comment]
@Nuklon - currently if you need to call a windows api, then yes. Implementing #304 will support an alternate solution if your app's usage of windows apis are internal (don't leak any types in method signatures or return values).

**Comment by Nuklon** [comment]
Thanks @AdamBraden, that's what I expected. I'll keep an eye out on #304.
