### ISSUE TITLE
Sample to ensure C#/WinRT supports IBackgroundTask (was Error :: Windows Metadata not provided or detected. )

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/CsWinRT#644]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Windows Metadata not provided or detected.  See https://github.com/microsoft/CsWinRT/tree/master/nuget/readme.md	.WinUI	C:\Users\Tommy\.nuget\packages\microsoft.windows.cswinrt\1.1.0\build\Microsoft.Windows.CsWinRT.targets	72	

I can't even seem to install this package. Microsoft.Windows.CsWinRT 1.1.0

How can I add a Windows Runtime Component to a WinUI project ?

**Comment by j0shuams** [comment]
You can't install CsWinRT? What is your `<TargetFramework>` in your project's `csproj` file?

**Comment by sigmarsson** [comment]
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>`

**Comment by angelazhangmsft** [comment]
Are you trying to create a projection for a WinRT component using CsWinRT? You may have to add the property $(CsWinRTWindowsMetadata) to your project file to get rid of that error.

**Comment by sigmarsson** [comment]
Great! Vanished. How can I add a Windows Runtime Component project reference to my WinUI ? 

Project AppService is not compatible with net5.0-windows10.0.18362 (.NETCoreApp,Version=v5.0). Project AppService supports: uap10.0.17134 (UAP,Version=v10.0.17134) WinUI	WinUI.csproj	1	

My AppService project is a Universal Windows having the references beneath;


![image](https://user-images.githubusercontent.com/43340959/102919939-0d0c0800-448a-11eb-9b85-7e47d32df78a.png)

**Comment by angelazhangmsft** [comment]
If you're using WinUI Preview 3 - currently the Desktop app templates support .NET 5, but not the UWP templates. If you're creating a Windows Runtime Component for a UWP app, it shouldn't be referencing CsWinRT.

**Comment by sigmarsson** [comment]
Thanks for your message. 

I am intending to forge just a standalone Windows Runtime Component - without UWP application - because this seems to be the only way to add an AppService to a WinUI application. [This ](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)is advising to host the service provider in a **Windows Runtime Component** project and - and some1 advised - I did hope CsWinRT has the capacity to integrate this component.

**Comment by angelazhangmsft** [comment]
microsoft/microsoft-ui-xaml#3838

**Comment by sigmarsson** [comment]
Could you acknowledge either its feasibility or an estimated future version, which will handle it?

**Comment by Scottj1s** [comment]
@sigmarsson, I'm trying to understand your scenario.  It sounds like you want your WinUI application to provide data to clients.  An AppService is appropriate for that, if your WinUI app is UWP.  In that case, the existing .NET Core 3.1 support for C# UWP Windows Runtime Components (project templates) should suffice.  If your WinUI application is Desktop, then an AppService is not appropriate, and you'd want to go with a named pipe or other IPC mechanism, as you mentioned in microsoft/microsoft-ui-xaml#3838.  If your WinUI app is a packaged Win32 (i.e., Centennial) app, then it could potentially register an AppService in the appx manifest, and you could implement that in C# with CsWinRT projection support for IBackgroundTask, etc.   That would in turn require CsWinRT authoring and [hosting support](https://github.com/microsoft/CsWinRT/blob/master/docs/hosting.md), so that native/managed clients could activate your managed AppService implementation.  Authoring support is work in progress, and should be available within a couple months.

**Comment by sigmarsson** [comment]
Exactly, `IBackgroundTask ` is the interface an AppService provider shall implement.
Is it advised to launch every new project as WinUI Desktop or both UWP and Desktop have their own benefits from a respective aspect ?

**Comment by Scottj1s** [comment]
Yes, there are tradeoffs for each platform. For details, see 
[Choose your Windows app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform).

**Comment by sigmarsson** [comment]
This is introducing the different flavours quite good. 
https://www.telerik.com/blogs/building-modern-performant-desktop-apps-winui-30-the-way-to-go

**Comment by sigmarsson** [comment]
I opted for gRpc named pipes, you answered my question. Thank you @Scottj1s
