### ISSUE TITLE
WinRT Memory Leak When Calling Windows.Graphics.Imaging.BitmapDecoder.CreateAsync on .NET 5

### ISSUE THREAD

**Issue by Xeio** [microsoft/CsWinRT#645]
**Describe the bug**
There seems to be an issue with Windows.Graphics.Imaging.BitmapDecoder.CreateAsync where it is leaking memory on .Net 5. This behavior does not occur on .Net Core 3.1 (memory stays relatively constant, within a variance due to GC).

The PNG file used does not seem to matter, though it's notable that the size of the leak seems to be proportional to the size of the PNG file.

Not sure if this is related to #640, since that's using the same API. I did see that issue when I was trying to MemoryStream/InMemoryRandomAccessStream. Using a FileRandomAccessStream never seems to throw an exception, instead it works correctly but consumes additional memory with each call. 

**To Reproduce**
1. Repeatedly call CreateAsync on BitmapDecoder from a stream.
2. Leak occurs

Project File (.Net 5)
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
  </PropertyGroup>
</Project>
```

Project File (.Net Core 3.1)
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Runtime.WindowsRuntime" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Windows">
      <HintPath>C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Windows.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
    </Reference>
  </ItemGroup>
</Project>
```

Code File:
```
using System;
using System.Threading.Tasks;
using Windows.Graphics.Imaging;
using Windows.Storage.Streams;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            for(int i = 0; i< 1000000; i++)
            {
                using var filestream = await FileRandomAccessStream.OpenAsync(@"C:\users\public\test.png", Windows.Storage.FileAccessMode.Read);
                var decoder = await BitmapDecoder.CreateAsync(BitmapDecoder.PngDecoderId, filestream);
            }
        }
    }
}
```

**Expected behavior**
Memory used should not continually increase, as in .Net Core 3.1.

**Version Info**
I checked net5.0-windows10.0.18362.0, though this seems to affect 19041 and earlier versions as well.

**Additional context**

**Comment by jbe2277** [comment]
I see similar memory leaks when using the `Windows.Storage` API.

My app is an open-source [WPF music player](https://jbe2277.github.io/musicmanager). 

In the Net5 branch I have activated multi-targeting so that it is possible to compare the behavior of the released version (.NET Framework 4.7.2 + Microsoft.Windows.SDK.Contracts package) with the behavior of using .NET 5.
https://github.com/jbe2277/musicmanager/commit/7a92c0b5df0887cdefbdc985a0fb0fbec64d9b16

Memory usage when searching for music files (Windows.Storage API)
- **.NET5**: The memory always increases. Tried it until >500 MB but it never decreased a bit.
- **.NET Framework 4.7.2**: the memory increases only for a short time and get freed again.

**Comment by azchohfi** [comment]
I'm having a similar issue with BitmapEncoder.

**Comment by tgudelj** [comment]
I was wondering what steps should be taken for .net 5 application affected by this issue once it gets remediated in CsWinRT, I mean, in 5.0 we reference Windows SDK, not Microsoft.Windows.SDK.Contracts package. Do I have to wait for next Windows SDK release or is there another more immediate solution?

**Comment by manodasanW** [comment]
@tgudelj Once it has been fixed in CsWinRT and if the fix is in either the Windows SDK projection or WinRT.Runtime like this one is in, we typically on a monthly basis do a Windows SDK projection update which the fix would be part of.  Then that Windows SDK projection would typically be included in the upcoming .NET 5 SDK servicing update and be available when you update to that version.

If you need to the fix before the .NET 5 SDK update comes out, you can do a framework reference update once the Windows SDK projection update is out like seen below where sdk_version is the windows sdk version you target and fix_version is the version with the fix.  You should remove this once the respective .NET 5 SDK servicing update is out.

```
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.<sdk_version>.<fix_version>" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.<sdk_version>.<fix_version>" />
</ItemGroup>
```
