### ISSUE TITLE
C#/WinRT component using WinUI types can't be hosted in WinUI 3 C++ Desktop app

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#725]
**Describe the bug**
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'. The system cannot find the file specified.' 
Our targets will need to add additional logic to copy over the net5 dependnecies of any dependent libraries.

**To Reproduce**

1. Author a C#/WinRT component, reference WinUI 3 Preview 4 NuGet, and author a type that extends WinUI type, for example:
```csharp
public sealed class CustomButton : Button {}
```
2. Consume as a package in a WinUI 3 Preview 4 C++ desktop (packaged) app. 
3. Get FileLoadException above when consuming the type. .NET 5 WinUI binaries isn't getting copied to Appx folder.

**Expected behavior**

**Version Info**

CsWinRT 1.1.2-prerelease.210205.6
WinUI 3.0.0-preview4.210204.7-CI

**Additional context**

**Comment by j0shuams** [comment]
I tried this with the targets I've been working on, and couldn't repro. Think this might be fixed, will get you nupkg to verify.

**Comment by j0shuams** [comment]
It looks like only native build assets are being copied out -- managed are not. I see Microsoft.WinUI.dll in the component's output, but when resolving the package assets for the c++ project, only native dlls are resolved.

**Comment by j0shuams** [comment]
This seems to be fixed by a nuget update... When you install the package, this happens. But if you run `nuget update` on the solution file, then [references get added](https://github.com/angelazhangmsft/WinUIAuthoringSample/blob/bbd84d420b2470d4fcd5c89d2a06e35ee591c9b4/CppWinUIDesktop/CppWinUIDesktop/CppWinUIDesktop.vcxproj#L152-L161) which provides the winmd that was missing. Seems like there is not work for us to do here, but would be best to get this story clear.

**Comment by j0shuams** [comment]
After an offline discussion, the nuget update fixed mentioned cannot be relied on. The solution we are going with is adding dependencies to the authored component's nupkg, and updating our transitive targets to copy the dependencies out in a referencing project
