### ISSUE TITLE
Update repo to build and test against Windows App SDK

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#778]
- new WinUI projection
- update WinUIDesktopSample to use new WinUI projection
- update objectlifetime test

**Comment by j0shuams** [comment]
There's a sample app I made as part of the PR above that I will add to this. 

Otherwise, this looks like stripping out all WinUI references and replacing them with Microsoft.ProjectReunion.WinUI references. 
We should consider dropping the WinUI projection and the WinUIDesktopSample. And we should rename the Reunion projection to WindowsAppSDK at some point...

**Comment by j0shuams** [comment]
Requirements:
[ ] Add a new projection for WinAppSDK 1.0.0 (or whatever the latest 1.0.x is)
[ ] Update ObjectLifetimeTests to use the new projection
[ ] Update WinUIDesktopSample to use the new projection
