### ISSUE TITLE
Hosting WinUI C# component: managed dependencies aren't placed in C++ output

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#955]
When authoring WinUI types in C# and consuming from C++, none of the managed dependencies are brought in with a project reference (missing Microsoft.WinUI.dll in the folder with the winmd/winrt.host)

**Comment by j0shuams** [comment]
This issue can be fixed by editing the vcxproj and updating the project reference like this: 
```xml
<ItemGroup>
  <ProjectReference Include="WinRTComponent.csproj">
    ...
    <Private>true</Private> 
  </ProjectReference>
</ItemGroup>
```

But it looks like the packaging project is causing some isssues. I got this error when building the wapproj 
```
Manifest references 'WinRT.Host.dll' which is not part of the payload. 
```
In the output directory, WinRT.Host.dll is not in the CppApp folder - but the component winmd is.

...


Running just the vcxproj's exe gave 
```
Exception thrown at 0x00007FFD5B2FA29C (KernelBase.dll) in CppApp.exe: WinRT originate error - 0x80040154 : 'Class not registered'.
```

**Comment by j0shuams** [comment]
Adding the metadata "Private" as "true" fixed this, but the issue remains of the assets not being in the right place. So this issue will work to track this.

**Comment by j0shuams** [comment]
@angelazhangmsft I think we can close this as this issue is gone. There does remain an issue with types not activating properly but might be better to have a new issue for that.

**Comment by angelazhangmsft** [comment]
@j0shuams sounds good, closing this issue
