### ISSUE TITLE
WinRT file uses single file dangerous pattern

### ISSUE THREAD

**Issue by tlakollo** [microsoft/CsWinRT#992]
**Describe the bug**
The [WinRT.cs](https://github.com/microsoft/CsWinRT/blob/master/src/cswinrt/strings/WinRT.cs#L110) file uses an [API incompatibility pattern](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility) for single file, using Assembly.Location will return an empty string, making `_currentModuleDirectory` to be an empty string.

This file is later on imported into the WPF repository, see https://github.com/dotnet/wpf/issues/5226
In order to be able to enable the single file analyzer in the WPF repository, all the warnings need to be addressed. For now, I will suppress the warning in the WPF repository pointing to this issue, and once addressed the WPF repo can be updated.

**Expected behavior**
When a warning is flagged the different remediation options are:
- Suppress the warning when the behavior is expected and handled by the code, or the code is not relevant for single-file scenarios
- Mark the code as single file dangerous with the attribute [RequiresAssemblyFiles]
- Remediate the code to handle the single file case

**Additional context**
For additional context of single-file deployment see the [documentation](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)

**Comment by manodasanW** [comment]
Looks like we should evaluate AppContext.BaseDirectory per the documentation.

**Comment by kant2002** [comment]
I would continue where https://github.com/microsoft/CsWinRT/pull/993#discussion_r713078862 left.

Seems to be single-file deployments with CsWinRT would be relatively hard to make right. Right now WinRT class activation happens in following fashion.
- `RoGetActivationFactory`
- Lookup in local folder for DLL names which has namespace names and then `DllGetActivationFactory`.

Theoretically I see 3 scenarios
1. System provided classes which are discoverable using `RoGetActivationFactory`
2. Developer provided classes in separate assemblies living side-by-side.
3. Globally installed 3rd-party classes discoverable using `RoGetActivationFactory`

From my understanding case 1 and 3 would work in singe-file deployment right even now, and warning does not affects anything, since `Assembly.GetExecutingAssembly()` call site would be never reached.

Let's look at case 2 now. Right now, for regular deployments `DllGetActivationFactory` function provided by CPP host which is bundled into produced DLL. For single-file packages seems to be host provided by .NET itself should export that function, and know how to look for the right class inside bundled DLLs.

What else I'm missing?

**Comment by agocke** [comment]
Sorry, trying to catch up here --it looks like this is to handle native code, right?

Single-file deployment has optional bundling and extraction of native components. I think there are a couple follow-up questions based on that: Who is expected to add the native components? The app developer or the end user?

If it's the app developer, they could credibly decide to either bundle the components for extraction, or just keep them next to the app. If it's the end user, there's no way to bundle after deployment, so you can always rely on the files being next to the app.

If the app developer decides to bundle the component, then the runtime should be able to find the DLL via `NATIVE_DLL_SEARCH_DIRECTORIES`. It looks like you're doing a manual `LoadLibrary` call, however. It seems like the best options might be to 1) check `NATIVE_DLL_SEARCH_DIRECTORIES` yourself, or 2) use a managed API for loading the native DLL.

@elinor-fung or @jkoritzinsky might have suggestions on the best way to load native assets in a way that takes `NATIVE_DLL_SEARCH_DIRECTORIES` into account.

**Comment by elinor-fung** [comment]
>  load native assets in a way that takes NATIVE_DLL_SEARCH_DIRECTORIES into account

[`NativeLibrary.Load(string, Assembly, DllImportSearchPath?)`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.nativelibrary.load#System_Runtime_InteropServices_NativeLibrary_Load_System_String_System_Reflection_Assembly_System_Nullable_System_Runtime_InteropServices_DllImportSearchPath__) should do this.
